// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rccxjlmaygshklepjdiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjY3hqbG1heWdzaGtsZXBqZGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxOTY5OTIsImV4cCI6MjA2Nzc3Mjk5Mn0.8jp4U6U8IssKmMSFzGk17MdDOhXm0EW9zo-xWViYQK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);